Lists/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url

app_name="Lists"
urlpatterns = [
    path('',views.showLists,name="showLists"),
    path('createlist/',views.createList,name="createList"),
    url(r'^(?P<slug>[\w-]+)/$',views.displayList,name="displayList"),
    url(r'^(?P<slug>[\w-]+)/additem/',views.addItem,name="addItem"),
    url(r'^(?P<slug>[\w-]+)/(?P<slug1>[\w-]+)/$',views.showItem,name="showItem"),
    url(r'^(?P<slug>[\w-]+)/(?P<slug1>[\w-]+)/adduser/$',views.addUser,name="addUser"),
    url(r'^(?P<slug>[\w-]+)/(?P<slug1>[\w-]+)/deleteitem/$',views.deleteItem,name="deleteItem"),
]

To_Do/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name="homepage"),
    path('accounts/',include('accounts.urls'),name="accounts"),
    # path('list/',include('list.urls'),name="list"),
    path('lists/',include('Lists.urls'),name="Lists")
]

accounts/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/',views.signup,name="signup"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    url('auth/',include('social_django.urls',namespace='accounts:social')),
]

Lists/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
# Create your models here.
class Lists(models.Model):
    name=models.CharField(max_length=400)
    slug=models.SlugField(unique=True)
    author=models.ManyToManyField(User,default=None)
    
    def __str__(self):
        return self.name

    def save(self):
        self.slug=slugify(self.name)
        super(Lists,self).save()

class Item(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    created_date=models.DateTimeField(auto_now_add=True)
    todo_date=models.DateTimeField(blank=True,null=True)
    slug=models.SlugField()
    author=models.ManyToManyField(User,default=None)
    lists=models.ForeignKey(Lists,on_delete=models.CASCADE,blank=False,default=None)
    
    def __str__(self):
        return self.title

    def save(self):
        self.slug=slugify(self.title)
        super(Item,self).save()

accounts/models.py
from django.db import models

# Create your models here.

Lists/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User

class Lists(forms.ModelForm):
    class Meta:
        model=models.Lists
        fields=['name']

class AddItem(forms.ModelForm):
    class Meta:
        model=models.Item
        fields=['title','description','todo_date']

class AddUser(forms.Form):
    username=forms.CharField(label='Enter username of the user you want to add',max_length=100)

Lists/views.py
from django.shortcuts import render,redirect
from .models import Lists,Item
from django.contrib.auth.decorators import login_required
from . import forms
from django.http import HttpResponse
from django.contrib.auth.models import User

# Create your views here.

@login_required(login_url="accounts:login")
def showLists(request):
    context={
        'lists':Lists.objects.filter(author=request.user)
    }
    return render(request,'Lists/showlists.html',context)

@login_required(login_url="accounts:login")
def createList(request):
    if request.method=='POST':
        form=forms.Lists(request.POST)
        if form.is_valid():
            instance=form.save()
            instance.save()
            instance.author.add(request.user)
            return redirect('Lists:showLists')
    else:
        form=forms.Lists()
    return render(request,'Lists/createlist.html',{'form':form})

@login_required(login_url="accounts:login")
def displayList(request,slug):
    l=Lists.objects.get(author=request.user,slug=slug)
    context={
        'list':Item.objects.filter(author=request.user ,lists=l),
        'slugoflist':slug,
        'listname':l.name,
    }
    return render(request,'Lists/displaylist.html',context)

@login_required(login_url="accounts:login")
def showItem(request,slug,slug1):
    try:
        l=Lists.objects.get(author=request.user,slug=slug)
        a=Item.objects.get(author=request.user ,slug=slug1,lists=l)
    except:
        a=None
    context={
        'item':a,
        'slugoflist':slug
    }
    return render(request,'Lists/showitem.html',context)
    

@login_required(login_url="accounts:login")
def addItem(request,slug):
    if request.method=='POST':
        form=forms.AddItem(request.POST)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.lists=Lists.objects.filter(author=request.user,slug=slug)[0]
            instance.save()
            instance.author.add(request.user)
            return redirect("Lists:displayList",slug=slug)
    else:
        form=forms.AddItem()
    return render(request,'Lists/additem.html',{'form':form,'slugoflist':slug})


@login_required(login_url="accounts:login")
def deleteItem(request,slug,slug1):
    try:
        l=Lists.objects.get(author=request.user,slug=slug)
        Item.objects.get(author=request.user,slug=slug1,lists=l).delete()
        # item.delete()
        return redirect("Lists:displayList",slug=slug)
    except:
        return HttpResponse("Error")

@login_required(login_url="account:login")
def addUser(request,slug,slug1):
    if request.method=='POST':
        form=forms.AddUser(request.POST)
        if form.is_valid():
            instance=request.POST
            l=Lists.objects.get(author=request.user,slug=slug)
            instance_item=Item.objects.get(author=request.user,lists=l,slug=slug1)
            user_to_add=User.objects.get(username=instance.get('username'))
            instance_item.author.add(user_to_add)
            l.author.add(user_to_add)
            return redirect("Lists:displayList",slug=slug)
    else:
        form=forms.AddUser()
    return render(request,'Lists/adduser.html',{'form':form,'slugofitem':slug1,'slugoflist':slug})
            
            

To_Do/views.py
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login as logi,logout as logo
# Create your views here.
def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            logi(request,user)
            return redirect('homepage')
    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout(request):
    if request.method=='POST':
        logo(request)
        return redirect('homepage')

Lists/templates/Lists/additem.html
{% extends 'base.html' %}
{% block title %}
Add new task
{% endblock title %}
{% block body %}
    <h2>Add a new task</h2>
    <form class="" action="{% url 'Lists:addItem' slug=slugoflist %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add Task">
    </form>
{% endblock body%}

Lists/templates/Lists/adduser.html
{% extends 'base.html' %}
{% block title %}
Add a User
{% endblock title %}
{% block body %}
    <h2>Add a User for this Task</h2>
    <form class="" action="{% url 'Lists:addUser' slug=slugoflist slug1=slugofitem %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Add User">
    </form>
{% endblock body%}

Lists/templates/Lists/createlist.html
{% extends 'base.html' %}
{% block title %}
Create List
{% endblock title %}
{% block body %}
    <h2>Create a new list</h2>
    <form class="" action="{% url 'Lists:createList' %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create List">
    </form>
{% endblock body%}

Lists/templates/Lists/displaylist.html
{% extends 'base.html' %}
{% block title %}
List
{% endblock %}
{% block body %}
    <ul>
    <a href="{% url 'Lists:showLists' %}"><input type="button" value="Show All Lists"></input></a>
    <h2><a href="{% url 'Lists:displayList' slug=slugoflist %}">{{listname}}</a></h2>
    <a href="{% url 'Lists:addItem' slug=slugoflist %}"><input type="submit" value="Add a new task"></a></br>
    {% for item in list %}
        <li>
            <h2><a href="{% url 'Lists:showItem' slug1=item.slug slug=slugoflist %}">{{item.title}}</a></h2>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

Lists/templates/Lists/showitem.html
{% extends 'base.html' %}
{% block title %}
Task
{% endblock %}
{% block body %}
    <p>Task</p>
    {% if item %}
        <a href="{% url 'Lists:addUser' slug=slugoflist slug1=item.slug %}"><input type="submit" value="Add a User"></a>
        <a href="{% url 'Lists:deleteItem' slug=slugoflist slug1=item.slug %}"><input type="submit" value="Delete this task"></a>
        <h2>{{item.title}}</h2>
        <p>{{item.description}}</p>
        <p>Created Date & Time : {{item.created_date}}</p>
        <p>To-Do Date & Time : {{item.todo_date}}<p>
    {% else %}
        <p>Item Does not Exist</p>
    {% endif %}
{% endblock %}

Lists/templates/Lists/showlists.html
{% extends 'base.html' %}
{% block title %}
Lists
{% endblock %}
{% block body %}
    <p>Lists</p>
    <ul>
    <a href="{% url 'Lists:createList' %}"><input type="submit" value="Create a new list"></a></br>
    {% for item in lists %}
        <li>
            <h2><a href="{% url 'Lists:displayList' slug=item.slug %}">{{item.name}}</a></h2>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
	Login
{% endblock title %}
{% block body %}
<h2>Login Page</h2>
	<form action="{% url 'accounts:login' %}" method="POST">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="Login">
	</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block title %}
	Signup
{% endblock title %}
{% block body %}
<h2>SignUp Page</h2>
	<form action="{% url 'accounts:signup' %}" method="POST">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="SignUp">
	</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}      
    {% endblock %} 
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <!-- <script src="main.js"></script> -->
</head>
<body>
    {% if user.is_authenticated %}
	    <form class="" action="{% url 'accounts:logout' %}" method="POST">
		{% csrf_token %}
	    <input type="submit" value="LogOut">
        </form>
    {% else %}
        <form class="" action="{% url 'accounts:login' %}" method="POST">
		{% csrf_token %}
	    <input type="submit" value="LogIn">
        </form>
        <form class="" action="{% url 'accounts:signup' %}" method="POST">
		{% csrf_token %}
	    <input type="submit" value="SignUp">
        </form>
        <p><strong>-- OR --</strong></p>
        <a href="{% url 'accounts:social:begin' 'google-oauth2' %}">Login with Google</a><br>
    {% endif %}
	{% block body %}	  
	{% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% block title %}
Welcome to my website
{% endblock title %}

{% block body %}
    <p>Welcome</p>
    <p>You can create a To-Do list here</p>
    {% if user.is_authenticated %}
        <a href="{% url 'Lists:showLists' %}"><input type="button" value="Show All Lists"></a>
        <a href="{% url 'Lists:createList' %}"><input type="button" value="Create a new list"></a>
    {% endif %}
{% endblock body %}